import SwiftSyntax

extension CodeBlockItemListSyntax: _RemovableSyntaxCollection { }
extension TupleExprElementListSyntax: _RemovableSyntaxCollection { }
extension ArrayElementListSyntax: _RemovableSyntaxCollection { }
extension DictionaryElementListSyntax: _RemovableSyntaxCollection { }
extension StringLiteralSegmentsSyntax: _RemovableSyntaxCollection { }
extension DeclNameArgumentListSyntax: _RemovableSyntaxCollection { }
extension ExprListSyntax: _RemovableSyntaxCollection { }
extension ClosureCaptureItemListSyntax: _RemovableSyntaxCollection { }
extension ClosureParamListSyntax: _RemovableSyntaxCollection { }
extension MultipleTrailingClosureElementListSyntax: _RemovableSyntaxCollection { }
extension ObjcNameSyntax: _RemovableSyntaxCollection { }
extension FunctionParameterListSyntax: _RemovableSyntaxCollection { }
extension IfConfigClauseListSyntax: _RemovableSyntaxCollection { }
extension InheritedTypeListSyntax: _RemovableSyntaxCollection { }
extension MemberDeclListSyntax: _RemovableSyntaxCollection { }
extension ModifierListSyntax: _RemovableSyntaxCollection { }
extension AccessPathSyntax: _RemovableSyntaxCollection { }
extension AccessorListSyntax: _RemovableSyntaxCollection { }
extension PatternBindingListSyntax: _RemovableSyntaxCollection { }
extension EnumCaseElementListSyntax: _RemovableSyntaxCollection { }
extension IdentifierListSyntax: _RemovableSyntaxCollection { }
extension PrecedenceGroupAttributeListSyntax: _RemovableSyntaxCollection { }
extension PrecedenceGroupNameListSyntax: _RemovableSyntaxCollection { }
extension TokenListSyntax: _RemovableSyntaxCollection { }
extension NonEmptyTokenListSyntax: _RemovableSyntaxCollection { }
extension AttributeListSyntax: _RemovableSyntaxCollection { }
extension SpecializeAttributeSpecListSyntax: _RemovableSyntaxCollection { }
extension ObjCSelectorSyntax: _RemovableSyntaxCollection { }
extension DifferentiabilityParamListSyntax: _RemovableSyntaxCollection { }
extension BackDeployVersionListSyntax: _RemovableSyntaxCollection { }
extension SwitchCaseListSyntax: _RemovableSyntaxCollection { }
extension CatchClauseListSyntax: _RemovableSyntaxCollection { }
extension CaseItemListSyntax: _RemovableSyntaxCollection { }
extension CatchItemListSyntax: _RemovableSyntaxCollection { }
extension ConditionElementListSyntax: _RemovableSyntaxCollection { }
extension GenericRequirementListSyntax: _RemovableSyntaxCollection { }
extension GenericParameterListSyntax: _RemovableSyntaxCollection { }
extension PrimaryAssociatedTypeListSyntax: _RemovableSyntaxCollection { }
extension CompositionTypeElementListSyntax: _RemovableSyntaxCollection { }
extension TupleTypeElementListSyntax: _RemovableSyntaxCollection { }
extension GenericArgumentListSyntax: _RemovableSyntaxCollection { }
extension TuplePatternElementListSyntax: _RemovableSyntaxCollection { }
extension AvailabilitySpecListSyntax: _RemovableSyntaxCollection { }
